### ISSUE TITLE
Bug: FIxing the video rendered on the homepage

### ISSUE THREAD

**Issue by saintmalik** [flipify/flipify#22]
There is a video thats meant to render on the homepage of https://flipify.dev, just like this 
![Screenshot 2022-10-06 at 7 18 55 AM](https://user-images.githubusercontent.com/37118134/194229256-fc749aa6-aeb4-4764-9fa8-b699311641d3.jpg)

Here is the video also;

**Comment by deven-533** [comment]
Can I take up this issue Sir?

**Comment by EmmanuelOluwafemi** [comment]
I will like to work on this task.

**Comment by saintmalik** [comment]
Great

**Comment by saintmalik** [comment]
> Can I take up this issue Sir?

@deven-533 should i assign another task for you, will this be okay?

**Comment by Fadahunsiseyi** [comment]
@saintmalik can you assign one to me?

**Comment by saintmalik** [comment]
> @saintmalik can you assign one to me?

ii just assigned @EmmanuelOluwafemi , will spin up more issues soon

**Comment by deven-533** [comment]
> > Can I take up this issue Sir?
> 
> @deven-533 should i assign another task for you, will this be okay?

Can you please elaborate another issue Sir?

**Comment by EmmanuelOluwafemi** [comment]
@saintmalik have pushed a pr for this issue https://github.com/flipify/flipify/pull/24

**Comment by saintmalik** [comment]
i just dropped a comment for you via the PR @EmmanuelOluwafemi

**Comment by saintmalik** [comment]
This issue is still open

**Comment by EmmanuelOluwafemi** [comment]
ohhh, omo I don forget will check it out this night

**Comment by saintmalik** [comment]
👀 👋

**Comment by saintmalik** [comment]
👀 👋

**Comment by saintmalik** [comment]
works not, thanks for your contribution
