### ISSUE TITLE
Add eslint and prettier for coding style check.

### ISSUE THREAD

**Issue by EmmanuelOluwafemi** [flipify/flipify#23]
Aligning contributor's code to follow a specific rule is essential to have a consistent code base, implementing ESLint and prettier check should help reformat the codebase and probably add husky or other commit checks to make sure all commit is properly checked before it's been pushed.

**Comment by Elijah699** [comment]
@EmmanuelOluwafemi are you working on this already?

**Comment by EmmanuelOluwafemi** [comment]
I don't think the issue as been approved

**Comment by saintmalik** [comment]
its available to be worked on

**Comment by saintmalik** [comment]
who is picking it up? @Elijah699 @EmmanuelOluwafemi

**Comment by Elijah699** [comment]
I will like to pick it up.

@EmmanuelOluwafemi should I go ahead? Since you created the issue.

**Comment by Elijah699** [comment]
@saintmalik hacktoberfest tag isn't added to this issue, is it going to count?

**Comment by saintmalik** [comment]
added, it counts

**Comment by Elijah699** [comment]
I will work on it @saintmalik, I've checked in with Emaz

**Comment by saintmalik** [comment]
great, i just assigned you

**Comment by saintmalik** [comment]
fixed in #30
